Task/run 37 run line chart
sam-kakengi/trackrunner pull request #22
Opened 2024-10-04 13:57 UTC by sam-kakengi

Finished correct API endpoint implementation and also fixed the chart's value formatting. Should work well across all responsive devices and a range of run data. Also removed route from the mobile view table and replaced with distance as discussed to avoid clunky viewing experience.

2024-10-04 14:20 UTC, Dimwiddle requested changes

2024-10-04 14:20 UTC, Dimwiddle commented on backend/running/views.py
> +            ]
Instead of running multiple loops, can you find a way of processing the chart data in one?

2024-10-04 14:20 UTC, Dimwiddle commented on backend/running/views.py
> +        print(f"Date range: {start_date} to {end_date}")
I don't think we need to have this logging anymore. Especially in production.

2024-10-04 14:20 UTC, Dimwiddle commented on frontend/src/components/core-components/dashboard/UserDrawer.js
> -                    <ListItem onClick={() => console.log('Logout clicked')}>
A heads up - You might want to merge this PR in before the Sign out Functionality PR, otherwise it'll give merge conflicts.

2024-10-04 14:20 UTC, Dimwiddle commented on frontend/src/components/core-components/dashboard/chart_components/LineChart.js
> + */
Do we need all these comments?

2024-10-04 14:20 UTC, Dimwiddle commented on frontend/src/theme/dashboard_themes/logRunModalTheme.js
> +      //   },
Can commented code be removed?

2024-10-04 14:20 UTC, Dimwiddle commented
Added some code comments, but will review the charts on my machine after work. Nice one @sam-kakengi  👌

2024-10-04 15:02 UTC, sam-kakengi commented on backend/running/views.py
> +            ]
Recent commit I think is the closest I can get, can you remind me how you fixed that doodle error regarding the backend  "No module named 'backend'"?

2024-10-04 15:19 UTC, Dimwiddle commented on backend/running/views.py
> +            ]
You need to have these two lines in the doodle file.

```
sys.path.append('/<mypath>/trackrunner/backend')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")
```

In the terminal `cd` in to  `backend/` then debug the file.

My one looks like below

```
import os
import django
import sys
sys.path.append('/Users/rkakengi/coding_projects/trackrunner/backend')
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")
django.setup()
from running.models import RunActivity, Route
from django.db.models import F
from django.db.models.functions import TruncDate
from datetime import date, datetime
from pprint import pprint
from datetime import relativedelta



if __name__ == "__main__":
    end_date = date.today() + relativedelta(days=1)
    start_date = end_date - relativedelta(months=3)
    active = list(RunActivity.objects.select_related('route').filter(user=2, finished__gte=start_date, finished__lte=end_date)
                  .annotate(date=TruncDate('finished'), route_name=F('route__name'))
                  .values('date', 'route_name').distinct())
    pprint(active)
```

2024-10-04 15:22 UTC, Dimwiddle commented on backend/running/views.py
> +        serializer = self.get_serializer(response_data)
Added a comment in serializers.py - I don't think you actually need this step. Try it out!

2024-10-04 16:22 UTC, sam-kakengi commented on backend/running/views.py
> +            ]
Cool thanks. Hmm, still struggling to find a way without using the nested loop, do you have a way?

2024-10-05 19:03 UTC, Dimwiddle commented on backend/running/views.py
> +            ]
This has been resolved now. Think it's all good.

2024-10-05 19:05 UTC, Dimwiddle commented on backend/running/views.py
> +        return Response(chart, status=status.HTTP_200_OK)
This is the final solution we should go with. It works well @sam-kakengi

2024-10-05 19:05 UTC, Dimwiddle approved these changes

2024-10-05 19:09 UTC, merged